/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Linda
 */
public class PerfilAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PerfilAdmin
     */
    public PerfilAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlperfilAdmin = new javax.swing.JPanel();
        Admin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInventarioAdm = new javax.swing.JButton();
        btnVentasAdm = new javax.swing.JButton();
        btnUusarioAdm = new javax.swing.JButton();
        btnClienteAdm = new javax.swing.JButton();
        btnTarjetaPtsAdm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(890, 676));

        pnlperfilAdmin.setBackground(new java.awt.Color(255, 255, 255));

        Admin.setBackground(new java.awt.Color(0, 93, 139));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRADOR");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/administrador.png"))); // NOI18N

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
        Admin.setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel2)
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addContainerGap(456, Short.MAX_VALUE))
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        btnInventarioAdm.setBackground(new java.awt.Color(0, 93, 139));
        btnInventarioAdm.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        btnInventarioAdm.setForeground(new java.awt.Color(255, 255, 255));
        btnInventarioAdm.setText("Inventario");
        btnInventarioAdm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInventarioAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioAdmActionPerformed(evt);
            }
        });

        btnVentasAdm.setBackground(new java.awt.Color(0, 93, 139));
        btnVentasAdm.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        btnVentasAdm.setForeground(new java.awt.Color(255, 255, 255));
        btnVentasAdm.setText("Ventas");
        btnVentasAdm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVentasAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasAdmActionPerformed(evt);
            }
        });

        btnUusarioAdm.setBackground(new java.awt.Color(0, 93, 139));
        btnUusarioAdm.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        btnUusarioAdm.setForeground(new java.awt.Color(255, 255, 255));
        btnUusarioAdm.setText("Uusuarios");
        btnUusarioAdm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUusarioAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUusarioAdmActionPerformed(evt);
            }
        });

        btnClienteAdm.setBackground(new java.awt.Color(0, 93, 139));
        btnClienteAdm.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        btnClienteAdm.setForeground(new java.awt.Color(255, 255, 255));
        btnClienteAdm.setText("Clientes");
        btnClienteAdm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClienteAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteAdmActionPerformed(evt);
            }
        });

        btnTarjetaPtsAdm.setBackground(new java.awt.Color(0, 93, 139));
        btnTarjetaPtsAdm.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        btnTarjetaPtsAdm.setForeground(new java.awt.Color(255, 255, 255));
        btnTarjetaPtsAdm.setText("Tarjeta de Puntos");
        btnTarjetaPtsAdm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarjetaPtsAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaPtsAdmActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/almacen.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/punto-de-venta.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clasificacion.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atencion-al-cliente.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjetas.png"))); // NOI18N

        javax.swing.GroupLayout pnlperfilAdminLayout = new javax.swing.GroupLayout(pnlperfilAdmin);
        pnlperfilAdmin.setLayout(pnlperfilAdminLayout);
        pnlperfilAdminLayout.setHorizontalGroup(
            pnlperfilAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlperfilAdminLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlperfilAdminLayout.createSequentialGroup()
                .addGroup(pnlperfilAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlperfilAdminLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnInventarioAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlperfilAdminLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3)))
                .addGap(71, 71, 71)
                .addGroup(pnlperfilAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVentasAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(94, 94, 94)
                .addGroup(pnlperfilAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlperfilAdminLayout.createSequentialGroup()
                        .addComponent(btnUusarioAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnClienteAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnTarjetaPtsAdm))
                    .addGroup(pnlperfilAdminLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel6)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlperfilAdminLayout.setVerticalGroup(
            pnlperfilAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlperfilAdminLayout.createSequentialGroup()
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(pnlperfilAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlperfilAdminLayout.createSequentialGroup()
                        .addGroup(pnlperfilAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33))
                    .addGroup(pnlperfilAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)))
                .addGap(56, 56, 56)
                .addGroup(pnlperfilAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVentasAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventarioAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUusarioAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienteAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTarjetaPtsAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlperfilAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlperfilAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarioAdmActionPerformed

    private void btnVentasAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasAdmActionPerformed

    private void btnUusarioAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUusarioAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUusarioAdmActionPerformed

    private void btnClienteAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteAdmActionPerformed

    private void btnTarjetaPtsAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaPtsAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarjetaPtsAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin;
    public javax.swing.JButton btnClienteAdm;
    public javax.swing.JButton btnInventarioAdm;
    public javax.swing.JButton btnTarjetaPtsAdm;
    public javax.swing.JButton btnUusarioAdm;
    public javax.swing.JButton btnVentasAdm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnlperfilAdmin;
    // End of variables declaration//GEN-END:variables
}
